import { HoraireLine, parseCSV } from '@/csv/horaires/parseCSV.js';
import { CodeSynop } from '@/csv/horaires/value-objects/CodeSynop.js';
import { CodeTemps } from '@/csv/horaires/value-objects/CodeTemps.js';
import { Etat } from '@/csv/horaires/value-objects/Etat.js';
import { HouleDirection } from '@/csv/horaires/value-objects/HouleDirection.js';
import { Visibility } from '@/csv/horaires/value-objects/Visibility.js';
import { HumiditeRelative } from '@/data/value-objects/HumiditeRelative.js';
import { Octa } from '@/data/value-objects/Octa.js';
import { PositiveFloat } from '@/data/value-objects/PositiveFloat.js';
import { PositiveInteger } from '@/data/value-objects/PositiveInteger.js';
import { Time } from '@/data/value-objects/Time.js';
import { UVIndex } from '@/data/value-objects/UVIndex.js';
import { WindDirection } from '@/data/value-objects/WindDirection.js';
import { IdStation } from '@/id-station/IdStation.js';
import { describe, expect, it } from 'vitest';

describe('parseCSV', () => {
    describe('parseCSV', () => {
        it('should parse the CSV', async () => {
            const csvLines = `POSTE;DATE;RR1;DRR1;HNEIGEF;NEIGETOT;T;TD;TN;HTN;TX;HTX;DG;T10;T20;T50;T100;TNSOL;TN50;TCHAUSSEE;TW;PSTAT;PMER;GEOP;PMERMIN;FF;DD;FXI;DXI;HXI;FXY;DXY;HXY;FF2;DD2;FXI2;DXI2;HXI2;FXI3S;DXI3S;HXI3S;U;UN;HUN;UX;HUX;UABS;DHUMI40;DHUMI80;DHUMEC;TSV;ENTH;INS;GLO;DIR;DIF;GLO2;UV;INFRAR;UV_INDICE;N;NBAS;CL;CM;CH;N1;C1;B1;N2;C2;B2;N3;B3;C3;N4;C4;B4;WW;VV;DVV200;W1;W2;SOL;SOLNG;TSNEIGE;TUBENEIGE;ESNEIGE;HNEIGEFI3;HNEIGEFI1;TMER;VVMER;ETATMER;DIRHOULE;TLAGON;UV2;INS2;INFRAR2;DIR2;DIF2
76116001;2024061512;0,0;0;;0;14,4;8,8;14,1;1105;14,5;1133;0;14,6;14,6;14,5;14,1;14,1;14,3;13,7;11,5;988,2;1006,7;;1006,7;6,4;210;13,8;230;1147;9,6;220;1119;;;;;;12,4;;1117;69;68;1119;72;1154;8,5;0;0;;11,3;32,2;0;46;;;47,0;;;;8;8;;;;8;;1080;;;;;;;;;;0;32800;0;;;;;;;;;;;;;;;;0;;;
76116001;2024061513;0,0;0;;0;15,2;10,2;14,2;1209;15,2;1300;0;14,6;14,6;14,5;14,1;14,2;14,0;13,7;12,5;987,9;1006,3;;1006,3;7,5;200;14,9;210;1204;8,7;210;1222;;;;;;13,6;;1210;72;68;1204;77;1237;9,3;0;0;;12,4;34,8;0;94;;;93,0;;;;8;3;;;;1;;720;3;;1080;7;1740;;;;;0;33235;0;;;;;;;;;;;;;;;;0;;;
76116001;2024061514;3.3;4;4;4;-5.5;-5.5;-5.5;1230;-5.5;1230;4;-5.5;-5.5;-5.5;-5.5;-5.5;-5.5;-5.5;-5.5;3.3;3.3;4;3.3;3.3;360;3.3;360;1230;3.3;360;1230;3.3;360;3.3;360;1230;3.3;360;1230;100;100;1230;100;1230;4;4;4;4;3.3;4;4;4;4;4;4;4;4;12;8;8;/;/;/;8;/;4;8;/;4;8;4;/;8;/;4;00;4;4;00;00;7;7;3.3;4;7;4;4;-5.5;6;7;999;-5.5;4;4;4;4;4
76116001;2024061515;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;`;
            const horaireLines = parseCSV(csvLines);
            expect(horaireLines.ok).toEqual<HoraireLine[]>([
                {
                    POSTE: IdStation.of('76116001'),
                    DATE: new Date('2024-06-15T12:00:00Z'),
                    RR1: PositiveFloat.of(0),
                    DRR1: PositiveInteger.of(0),
                    HNEIGEF: PositiveInteger.of(null),
                    NEIGETOT: PositiveInteger.of(0),
                    T: 14.4,
                    TD: 8.8,
                    TN: 14.1,
                    HTN: Time.of('1105'),
                    TX: 14.5,
                    HTX: Time.of('1133'),
                    DG: PositiveInteger.of(0),
                    T10: 14.6,
                    T20: 14.6,
                    T50: 14.5,
                    T100: 14.1,
                    TNSOL: 14.1,
                    TN50: 14.3,
                    TCHAUSSEE: 13.7,
                    TW: 11.5,
                    PSTAT: PositiveFloat.of(988.2),
                    PMER: PositiveFloat.of(1006.7),
                    GEOP: PositiveInteger.of(null),
                    PMERMIN: PositiveFloat.of(1006.7),
                    FF: PositiveFloat.of(6.4),
                    DD: WindDirection.of(PositiveInteger.of(210)),
                    FXI: PositiveFloat.of(13.8),
                    DXI: WindDirection.of(PositiveInteger.of(230)),
                    HXI: Time.of('1147'),
                    FXY: PositiveFloat.of(9.6),
                    DXY: WindDirection.of(PositiveInteger.of(220)),
                    HXY: Time.of('1119'),
                    FF2: PositiveFloat.of(null),
                    DD2: WindDirection.of(PositiveInteger.of(null)),
                    FXI2: PositiveFloat.of(null),
                    DXI2: WindDirection.of(PositiveInteger.of(null)),
                    HXI2: Time.of(''),
                    FXI3S: PositiveFloat.of(12.4),
                    DXI3S: WindDirection.of(PositiveInteger.of(null)),
                    HXI3S: Time.of('1117'),
                    U: HumiditeRelative.of(69),
                    UN: HumiditeRelative.of(68),
                    HUN: Time.of('1119'),
                    UX: HumiditeRelative.of(72),
                    HUX: Time.of('1154'),
                    UABS: PositiveFloat.of(8.5),
                    DHUMI40: PositiveInteger.of(0),
                    DHUMI80: PositiveInteger.of(0),
                    DHUMEC: PositiveInteger.of(null),
                    TSV: PositiveFloat.of(11.3),
                    ENTH: PositiveFloat.of(32.2),
                    INS: PositiveInteger.of(0),
                    GLO: PositiveInteger.of(46),
                    DIR: PositiveInteger.of(null),
                    DIF: PositiveInteger.of(null),
                    GLO2: PositiveInteger.of(47.0),
                    UV: PositiveInteger.of(null),
                    INFRAR: PositiveInteger.of(null),
                    UV_INDICE: UVIndex.of(PositiveInteger.of(null)),
                    N: Octa.of(PositiveInteger.of(8)),
                    NBAS: Octa.of(PositiveInteger.of(8)),
                    CL: CodeSynop.of(''),
                    CM: CodeSynop.of(''),
                    CH: CodeSynop.of(''),
                    N1: Octa.of(PositiveInteger.of(8)),
                    C1: CodeSynop.of(''),
                    B1: PositiveInteger.of(1080),
                    N2: Octa.of(PositiveInteger.of(null)),
                    C2: CodeSynop.of(''),
                    B2: PositiveInteger.of(null),
                    N3: Octa.of(PositiveInteger.of(null)),
                    B3: PositiveInteger.of(null),
                    C3: CodeSynop.of(''),
                    N4: Octa.of(PositiveInteger.of(null)),
                    C4: CodeSynop.of(''),
                    B4: PositiveInteger.of(null),
                    WW: CodeTemps.of('00'),
                    VV: PositiveInteger.of(32800),
                    DVV200: PositiveInteger.of(0),
                    W1: CodeTemps.of(''),
                    W2: CodeTemps.of(''),
                    SOL: Etat.of(PositiveInteger.of(null)),
                    SOLNG: Etat.of(PositiveInteger.of(null)),
                    TSNEIGE: PositiveFloat.of(null),
                    TUBENEIGE: PositiveInteger.of(null),
                    ESNEIGE: Etat.of(PositiveInteger.of(null)),
                    HNEIGEFI3: PositiveInteger.of(null),
                    HNEIGEFI1: PositiveInteger.of(null),
                    TMER: null,
                    VVMER: Visibility.of(PositiveInteger.of(null)),
                    ETATMER: Etat.of(PositiveInteger.of(null)),
                    DIRHOULE: HouleDirection.of(PositiveInteger.of(null)),
                    TLAGON: null,
                    UV2: PositiveInteger.of(null),
                    INS2: PositiveInteger.of(0),
                    INFRAR2: PositiveInteger.of(null),
                    DIR2: PositiveInteger.of(null),
                    DIF2: PositiveInteger.of(null),
                },
                {
                    POSTE: IdStation.of('76116001'),
                    DATE: new Date('2024-06-15T13:00:00Z'),
                    RR1: PositiveFloat.of(0),
                    DRR1: PositiveInteger.of(0),
                    HNEIGEF: PositiveInteger.of(null),
                    NEIGETOT: PositiveInteger.of(0),
                    T: 15.2,
                    TD: 10.2,
                    TN: 14.2,
                    HTN: Time.of('1209'),
                    TX: 15.2,
                    HTX: Time.of('1300'),
                    DG: PositiveInteger.of(0),
                    T10: 14.6,
                    T20: 14.6,
                    T50: 14.5,
                    T100: 14.1,
                    TNSOL: 14.2,
                    TN50: 14.0,
                    TCHAUSSEE: 13.7,
                    TW: 12.5,
                    PSTAT: PositiveFloat.of(987.9),
                    PMER: PositiveFloat.of(1006.3),
                    GEOP: PositiveInteger.of(null),
                    PMERMIN: PositiveFloat.of(1006.3),
                    FF: PositiveFloat.of(7.5),
                    DD: WindDirection.of(PositiveInteger.of(200)),
                    FXI: PositiveFloat.of(14.9),
                    DXI: WindDirection.of(PositiveInteger.of(210)),
                    HXI: Time.of('1204'),
                    FXY: PositiveFloat.of(8.7),
                    DXY: WindDirection.of(PositiveInteger.of(210)),
                    HXY: Time.of('1222'),
                    FF2: PositiveFloat.of(null),
                    DD2: WindDirection.of(PositiveInteger.of(null)),
                    FXI2: PositiveFloat.of(null),
                    DXI2: WindDirection.of(PositiveInteger.of(null)),
                    HXI2: Time.of(''),
                    FXI3S: PositiveFloat.of(13.6),
                    DXI3S: WindDirection.of(PositiveInteger.of(null)),
                    HXI3S: Time.of('1210'),
                    U: HumiditeRelative.of(72),
                    UN: HumiditeRelative.of(68),
                    HUN: Time.of('1204'),
                    UX: HumiditeRelative.of(77),
                    HUX: Time.of('1237'),
                    UABS: PositiveFloat.of(9.3),
                    DHUMI40: PositiveInteger.of(0),
                    DHUMI80: PositiveInteger.of(0),
                    DHUMEC: PositiveInteger.of(null),
                    TSV: PositiveFloat.of(12.4),
                    ENTH: PositiveFloat.of(34.8),
                    INS: PositiveInteger.of(0),
                    GLO: PositiveInteger.of(94),
                    DIR: PositiveInteger.of(null),
                    DIF: PositiveInteger.of(null),
                    GLO2: PositiveInteger.of(93),
                    UV: PositiveInteger.of(null),
                    INFRAR: PositiveInteger.of(null),
                    UV_INDICE: UVIndex.of(PositiveInteger.of(null)),
                    N: Octa.of(PositiveInteger.of(8)),
                    NBAS: Octa.of(PositiveInteger.of(3)),
                    CL: CodeSynop.of(''),
                    CM: CodeSynop.of(''),
                    CH: CodeSynop.of(''),
                    N1: Octa.of(PositiveInteger.of(1)),
                    C1: CodeSynop.of(''),
                    B1: PositiveInteger.of(720),
                    N2: Octa.of(PositiveInteger.of(3)),
                    C2: CodeSynop.of(''),
                    B2: PositiveInteger.of(1080),
                    N3: Octa.of(PositiveInteger.of(7)),
                    B3: PositiveInteger.of(1740),
                    C3: CodeSynop.of(''),
                    N4: Octa.of(PositiveInteger.of(null)),
                    C4: CodeSynop.of(''),
                    B4: PositiveInteger.of(null),
                    WW: CodeTemps.of('00'),
                    VV: PositiveInteger.of(33235),
                    DVV200: PositiveInteger.of(0),
                    W1: CodeTemps.of(''),
                    W2: CodeTemps.of(''),
                    SOL: Etat.of(PositiveInteger.of(null)),
                    SOLNG: Etat.of(PositiveInteger.of(null)),
                    TSNEIGE: PositiveFloat.of(null),
                    TUBENEIGE: PositiveInteger.of(null),
                    ESNEIGE: Etat.of(PositiveInteger.of(null)),
                    HNEIGEFI3: PositiveInteger.of(null),
                    HNEIGEFI1: PositiveInteger.of(null),
                    TMER: null,
                    VVMER: Visibility.of(PositiveInteger.of(null)),
                    ETATMER: Etat.of(PositiveInteger.of(null)),
                    DIRHOULE: HouleDirection.of(PositiveInteger.of(null)),
                    TLAGON: null,
                    UV2: PositiveInteger.of(null),
                    INS2: PositiveInteger.of(0),
                    INFRAR2: PositiveInteger.of(null),
                    DIR2: PositiveInteger.of(null),
                    DIF2: PositiveInteger.of(null), //
                },
                {
                    POSTE: IdStation.of('76116001'),
                    DATE: new Date('2024-06-15T14:00:00Z'),
                    RR1: PositiveFloat.of(3.3),
                    DRR1: PositiveInteger.of(4),
                    HNEIGEF: PositiveInteger.of(4),
                    NEIGETOT: PositiveInteger.of(4),
                    T: -5.5,
                    TD: -5.5,
                    TN: -5.5,
                    HTN: Time.of('1230'),
                    TX: -5.5,
                    HTX: Time.of('1230'),
                    DG: PositiveInteger.of(4),
                    T10: -5.5,
                    T20: -5.5,
                    T50: -5.5,
                    T100: -5.5,
                    TNSOL: -5.5,
                    TN50: -5.5,
                    TCHAUSSEE: -5.5,
                    TW: -5.5,
                    PSTAT: PositiveFloat.of(3.3),
                    PMER: PositiveFloat.of(3.3),
                    GEOP: PositiveInteger.of(4),
                    PMERMIN: PositiveFloat.of(3.3),
                    FF: PositiveFloat.of(3.3),
                    DD: WindDirection.of(PositiveInteger.of(360)),
                    FXI: PositiveFloat.of(3.3),
                    DXI: WindDirection.of(PositiveInteger.of(360)),
                    HXI: Time.of('1230'),
                    FXY: PositiveFloat.of(3.3),
                    DXY: WindDirection.of(PositiveInteger.of(360)),
                    HXY: Time.of('1230'),
                    FF2: PositiveFloat.of(3.3),
                    DD2: WindDirection.of(PositiveInteger.of(360)),
                    FXI2: PositiveFloat.of(3.3),
                    DXI2: WindDirection.of(PositiveInteger.of(360)),
                    HXI2: Time.of('1230'),
                    FXI3S: PositiveFloat.of(3.3),
                    DXI3S: WindDirection.of(PositiveInteger.of(360)),
                    HXI3S: Time.of('1230'),
                    U: HumiditeRelative.of(100),
                    UN: HumiditeRelative.of(100),
                    HUN: Time.of('1230'),
                    UX: HumiditeRelative.of(100),
                    HUX: Time.of('1230'),
                    UABS: PositiveFloat.of(4),
                    DHUMI40: PositiveInteger.of(4),
                    DHUMI80: PositiveInteger.of(4),
                    DHUMEC: PositiveInteger.of(4),
                    TSV: PositiveFloat.of(3.3),
                    ENTH: PositiveFloat.of(4),
                    INS: PositiveInteger.of(4),
                    GLO: PositiveInteger.of(4),
                    DIR: PositiveInteger.of(4),
                    DIF: PositiveInteger.of(4),
                    GLO2: PositiveInteger.of(4),
                    UV: PositiveInteger.of(4),
                    INFRAR: PositiveInteger.of(4),
                    UV_INDICE: UVIndex.of(PositiveInteger.of(12)),
                    N: Octa.of(PositiveInteger.of(8)),
                    NBAS: Octa.of(PositiveInteger.of(8)),
                    CL: CodeSynop.of('/'),
                    CM: CodeSynop.of('/'),
                    CH: CodeSynop.of('/'),
                    N1: Octa.of(PositiveInteger.of(8)),
                    C1: CodeSynop.of('/'),
                    B1: PositiveInteger.of(4),
                    N2: Octa.of(PositiveInteger.of(8)),
                    C2: CodeSynop.of('/'),
                    B2: PositiveInteger.of(4),
                    N3: Octa.of(PositiveInteger.of(8)),
                    B3: PositiveInteger.of(4),
                    C3: CodeSynop.of('/'),
                    N4: Octa.of(PositiveInteger.of(8)),
                    C4: CodeSynop.of('/'),
                    B4: PositiveInteger.of(4),
                    WW: CodeTemps.of('00'),
                    VV: PositiveInteger.of(4),
                    DVV200: PositiveInteger.of(4),
                    W1: CodeTemps.of('00'),
                    W2: CodeTemps.of('00'),
                    SOL: Etat.of(PositiveInteger.of(7)),
                    SOLNG: Etat.of(PositiveInteger.of(7)),
                    TSNEIGE: PositiveFloat.of(3.3),
                    TUBENEIGE: PositiveInteger.of(4),
                    ESNEIGE: Etat.of(PositiveInteger.of(7)),
                    HNEIGEFI3: PositiveInteger.of(4),
                    HNEIGEFI1: PositiveInteger.of(4),
                    TMER: -5.5,
                    VVMER: Visibility.of(PositiveInteger.of(6)),
                    ETATMER: Etat.of(PositiveInteger.of(7)),
                    DIRHOULE: HouleDirection.of(PositiveInteger.of(999)),
                    TLAGON: -5.5,
                    UV2: PositiveInteger.of(4),
                    INS2: PositiveInteger.of(4),
                    INFRAR2: PositiveInteger.of(4),
                    DIR2: PositiveInteger.of(4),
                    DIF2: PositiveInteger.of(4),
                },
                {
                    POSTE: IdStation.of('76116001'),
                    DATE: new Date('2024-06-15T15:00:00Z'),
                    RR1: PositiveFloat.of(null),
                    DRR1: PositiveInteger.of(null),
                    HNEIGEF: PositiveInteger.of(null),
                    NEIGETOT: PositiveInteger.of(null),
                    T: null,
                    TD: null,
                    TN: null,
                    HTN: Time.of(''),
                    TX: null,
                    HTX: Time.of(''),
                    DG: PositiveInteger.of(null),
                    T10: null,
                    T20: null,
                    T50: null,
                    T100: null,
                    TNSOL: null,
                    TN50: null,
                    TCHAUSSEE: null,
                    TW: null,
                    PSTAT: PositiveFloat.of(null),
                    PMER: PositiveFloat.of(null),
                    GEOP: PositiveInteger.of(null),
                    PMERMIN: PositiveFloat.of(null),
                    FF: PositiveFloat.of(null),
                    DD: WindDirection.of(PositiveInteger.of(null)),
                    FXI: PositiveFloat.of(null),
                    DXI: WindDirection.of(PositiveInteger.of(null)),
                    HXI: Time.of(''),
                    FXY: PositiveFloat.of(null),
                    DXY: WindDirection.of(PositiveInteger.of(null)),
                    HXY: Time.of(''),
                    FF2: PositiveFloat.of(null),
                    DD2: WindDirection.of(PositiveInteger.of(null)),
                    FXI2: PositiveFloat.of(null),
                    DXI2: WindDirection.of(PositiveInteger.of(null)),
                    HXI2: Time.of(''),
                    FXI3S: PositiveFloat.of(null),
                    DXI3S: WindDirection.of(PositiveInteger.of(null)),
                    HXI3S: Time.of(''),
                    U: HumiditeRelative.of(null),
                    UN: HumiditeRelative.of(null),
                    HUN: Time.of(''),
                    UX: HumiditeRelative.of(null),
                    HUX: Time.of(''),
                    UABS: PositiveFloat.of(null),
                    DHUMI40: PositiveInteger.of(null),
                    DHUMI80: PositiveInteger.of(null),
                    DHUMEC: PositiveInteger.of(null),
                    TSV: PositiveFloat.of(null),
                    ENTH: PositiveFloat.of(null),
                    INS: PositiveInteger.of(null),
                    GLO: PositiveInteger.of(null),
                    DIR: PositiveInteger.of(null),
                    DIF: PositiveInteger.of(null),
                    GLO2: PositiveInteger.of(null),
                    UV: PositiveInteger.of(null),
                    INFRAR: PositiveInteger.of(null),
                    UV_INDICE: UVIndex.of(PositiveInteger.of(null)),
                    N: Octa.of(PositiveInteger.of(null)),
                    NBAS: Octa.of(PositiveInteger.of(null)),
                    CL: CodeSynop.of(''),
                    CM: CodeSynop.of(''),
                    CH: CodeSynop.of(''),
                    N1: Octa.of(PositiveInteger.of(null)),
                    C1: CodeSynop.of(''),
                    B1: PositiveInteger.of(null),
                    N2: Octa.of(PositiveInteger.of(null)),
                    C2: CodeSynop.of(''),
                    B2: PositiveInteger.of(null),
                    N3: Octa.of(PositiveInteger.of(null)),
                    B3: PositiveInteger.of(null),
                    C3: CodeSynop.of(''),
                    N4: Octa.of(PositiveInteger.of(null)),
                    C4: CodeSynop.of(''),
                    B4: PositiveInteger.of(null),
                    WW: CodeTemps.of(''),
                    VV: PositiveInteger.of(null),
                    DVV200: PositiveInteger.of(null),
                    W1: CodeTemps.of(''),
                    W2: CodeTemps.of(''),
                    SOL: Etat.of(PositiveInteger.of(null)),
                    SOLNG: Etat.of(PositiveInteger.of(null)),
                    TSNEIGE: PositiveFloat.of(null),
                    TUBENEIGE: PositiveInteger.of(null),
                    ESNEIGE: Etat.of(PositiveInteger.of(null)),
                    HNEIGEFI3: PositiveInteger.of(null),
                    HNEIGEFI1: PositiveInteger.of(null),
                    TMER: null,
                    VVMER: Visibility.of(PositiveInteger.of(null)),
                    ETATMER: Etat.of(PositiveInteger.of(null)),
                    DIRHOULE: HouleDirection.of(PositiveInteger.of(null)),
                    TLAGON: null,
                    UV2: PositiveInteger.of(null),
                    INS2: PositiveInteger.of(null),
                    INFRAR2: PositiveInteger.of(null),
                    DIR2: PositiveInteger.of(null),
                    DIF2: PositiveInteger.of(null),
                },
            ]);
        });
    });
});
